spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:dictionary
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    open-in-view: false

  output:
    ansi:
      enabled: always

  cache:
    type: caffeine
    cache-names:
      - statistics
    caffeine:
      spec: maximumSize=100,expireAfterWrite=300s

server:
  port: 8888
  servlet:
    session:
      timeout: 30m

logging:
  level:
    root: info
    com.freeadddictionary: info