spring:
  datasource:
    url: jdbc:h2:mem:dictionary
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        # format_sql: true
        # show_sql: true

  output:
    ansi:
      enabled: always

server:
  port: 8888
  servlet:
    session:
      timeout: 30m

logging:
  level:
    com.freeadddictionary: debug