spring:
  datasource:
    url: jdbc:h2:mem:dictionary
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  sql:
    init:
      encoding: UTF-8

  output:
    ansi:
      enabled: always

server:
  port: 8888
  servlet:
    session:
      timeout: 30m

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.freeadddictionary: debug

  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"